### ISSUE TITLE
JsonLdParser "@container": "@list"  Uncaught TypeError

### ISSUE THREAD

**Issue by elf-pavlik** [zazukoians/rdf-ext#17]
i don't have time to investigate so i report very quickly *apologies!*
trying to parse JSON-LD as in

http://json-ld.org/playground/#/gist/dd7b8aa090f107970376

i endup with 

```shell
 Uncaught TypeError: Cannot call method 'toString' of undefined
      at new rdf.Literal (/cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-interfaces/rdfi.js:129:146)
      at Object.defineProperties.createLiteral.value [as createLiteral] (/cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-interfaces/rdfi.js:377:16)
      at getLiteral (/cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/lib/jsonld-parser.js:79:18)
      at processObject (/cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/lib/jsonld-parser.js:152:14)
      at /cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/lib/jsonld-parser.js:136:11
      at Array.forEach (native)
      at processPredicate (/cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/lib/jsonld-parser.js:132:16)
      at processSubject (/cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/lib/jsonld-parser.js:127:9)
      at /cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/lib/jsonld-parser.js:161:9
      at Array.forEach (native)
      at /cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/lib/jsonld-parser.js:160:14
      at /cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/lib/jsonld-parser.js:32:9
      at /cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/node_modules/jsonld/js/jsonld.js:438:7
      at cleanup (/cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/node_modules/jsonld/js/jsonld.js:231:5)
      at /cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/node_modules/jsonld/js/jsonld.js:164:7
      at /cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/node_modules/jsonld/js/jsonld.js:1925:5
      at finished (/cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/node_modules/jsonld/js/jsonld.js:6177:7)
      at _retrieveContextUrls.retrieve (/cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/node_modules/jsonld/js/jsonld.js:6183:7)
      at _retrieveContextUrls (/cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/node_modules/jsonld/js/jsonld.js:6282:3)
      at Function.jsonld.processContext (/cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/node_modules/jsonld/js/jsonld.js:1915:3)
      at /cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/node_modules/jsonld/js/jsonld.js:149:12
      at /cache/code/w3c/w3c-socialwg-activitystreams/node_modules/rdf-ext/node_modules/jsonld/js/jsonld.js:133:16
      at process._tickCallback (node.js:415:13)

```
you could also try uncomment https://github.com/elf-pavlik/w3c-socialwg-activitystreams/commit/f1d58658f5165d07bd2b1277401453da21c869a1#diff-03d2e724d369f2635fc123f85d486fbbR145
and run

```shell
npm install
./node_modules/.bin/mocha -g ordered test
```

**when i remove this line it doesn't crash!**
https://github.com/elf-pavlik/w3c-socialwg-activitystreams/blob/f1d58658f5165d07bd2b1277401453da21c869a1/activitystreams2-context.jsonld#L233

**Comment by bergos** [comment]
I added list support to the JSON-LD parser in version 0.1.9. Now RDF-Ext should parse your example.

**Comment by elf-pavlik** [comment]
thank you! :bow:
