### ISSUE TITLE
Test fails: Turtle serializer should generate parsable card

### ISSUE THREAD

**Issue by nicola** [zazukoians/rdf-ext#40]
See [travis#3](https://travis-ci.org/zazukoians/rdf-ext/builds/76688956)

```
Error: Expected prefix to follow @prefix at line 9.
      at Object.N3Parser._error (/Users/mozilla/Proj/gits/rdf-ext/node_modules/n3/lib/N3Parser.js:570:20)
      at Object.N3Parser._readPrefix (/Users/mozilla/Proj/gits/rdf-ext/node_modules/n3/lib/N3Parser.js:488:19)
      at /Users/mozilla/Proj/gits/rdf-ext/node_modules/n3/lib/N3Parser.js:619:35
      at Object.N3Lexer._tokenizeToEnd (/Users/mozilla/Proj/gits/rdf-ext/node_modules/n3/lib/N3Lexer.js:284:7)
      at Object._onImmediate (/Users/mozilla/Proj/gits/rdf-ext/node_modules/n3/lib/N3Lexer.js:340:38)
      at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by nicola** [comment]
Maybe also @RubenVerborgh can give us some hints?

**Comment by RubenVerborgh** [comment]
I can give hints, but need more context. What are the exact generated contents?

**Comment by bergos** [comment]
Sorry to disturb you. I fixed the error 1 minute after you posted the comment. It was caused by a wrong import of prefixes from the JSON-LD context.

**Comment by nicola** [comment]
brilliant, thanks a lot for your super fast replies (and fixes) :)

**Comment by nicola** [comment]
Fixed in https://github.com/zazukoians/rdf-ext/commit/212b5b52ee5f9a1dd43cd0732c0d9d6239828c1a
